---
abstract: ~
author:
  - 'Simon Elsbrock <simon@iodev.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cashpoint-Terminal
no_index:
  directory:
    - inc
    - t
requires:
  AnyEvent::HTTP: 0
  Device::SerialPort: 0
  JSON::XS: 0
  Log::Log4perl: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
